---
title: "Week1"
author: "Yalin Yang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  word_document:
    toc: no
    toc_depth: '3'
  html_document:
    toc: no
    toc_depth: '3'
    df_print: paged
---

## Extensions of Scatterplots

```{r warning=FALSE}
library(tidyverse)
cces <- drop_na(read.csv(url("https://www.dropbox.com/s/ahmt12y39unicd2/cces_sample_coursera.csv?raw=1")))
cel <- read.csv(url("https://www.dropbox.com/s/4ebgnkdhhxo5rac/cel_volden_wiseman%20_coursera.csv?raw=1"))
```

```{r}
ggplot(cces,aes(x = educ,y=ideo5)) + 
  geom_jitter()
```

`geom_smooth()` using method = 'loess' and formula 'y ~ x'

```{r warning=FALSE}
ggplot(cces,aes(x=educ,y=ideo5)) + 
  geom_jitter()+
  geom_smooth()
```

```{r}
ggplot(cces,aes(x = educ,y=ideo5))+
  geom_jitter() + 
  geom_smooth(method = "lm",level = 0.9)
```

```{r warning=FALSE}
# install.packages("GGally")
library(GGally)
```

```{r}
set.seed(1234)
var1 <- runif(100,min = 0,max = 1)
var2 <-var1 + rnorm(n = 100, mean = 1,sd = .2)
var3 <-var1 * (-rnorm(100,mean = 1,sd = .2))
df <-tibble(var1,var2,var3)
head(df)
```

```{r}
ggpairs(df)
```

```{r}
my_scatter <- function(data,mapping){
  ggplot(data=data,mapping = mapping) + 
    geom_jitter(color = "blue")
}

my_density <- function(data,mapping){
  ggplot(data = data, mapping = mapping) + 
    geom_density(alpha = .05,fill = 'red')
}


ggpairs(df,
        lower = list(continuous = my_scatter),
        diag = list(continuous = my_density))
```

```{r}
library(ggcorrplot)
library(ggthemes)
```

```{r}
df <- cces %>% select("educ","pid7","pew_religimp")
r <- cor(df,use = "complete.obs")
ggcorrplot(r)
```

```{r}
ggcorrplot(r,type = "lower")
```

```{r}
ggcorrplot(r,type = "lower",
           title = "Correlations",
           colors = c("yellow","green","blue"),
           outline.color = "purple")
```

```{r}
ggcorrplot(r,type = "lower",title = "Correlations",
           ggtheme = theme_wsj())
```

### Cleveland Dot Plots

```{r}
cel_114 <- cel %>% filter(congress == 114)
members <- sample_n(cel_114,25)

ggplot(members,aes(x=les,y=thomas_name)) + 
  geom_point()
```

```{r}
ggplot(members,aes(x=les,y=thomas_name)) + 
  geom_point(size = 5) + 
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(linetype = "dashed",color = "blue"))+
  labs(x="Legislative Effectiveness",y="")
```
### Lollipop figure

```{r}
# ?reorder
ggplot(members,aes(x = reorder(thomas_name,les),y=les)) + 
  geom_point() + 
  geom_segment(aes(x = thomas_name,xend = thomas_name, y = 0, yend = les)) + 
  theme(axis.text.x = element_text(angle = 90))
  
```

## Variations on Line Plots

```{r}
set.seed(12345)
var1 <- runif(n = 10,min = 0,max = 25)
time <-  seq(1:10)
df <- tibble(var1,time)
head(df)
ggplot(df,aes(x = time,y=var1)) + 
  geom_area()
```

```{r warning=FALSE}
ggplot(df,aes(x = time,y=var1,fill = "red")) + 
  geom_area() + 
  guides(fill = FALSE) # drop the legend
```

### Stacked line graph

```{r}
set.seed(1234)
Bob <- tibble(person = rep("Bob",5),time = seq(1:5),change = runif(5,0,25))
Sue <- tibble(person = rep("Sue",5),time = seq(1:5),change = runif(5,0,25))
Lisa <- tibble(person = rep("Lisa",5),time = seq(1:5),change = runif(5,0,25))

df <- bind_rows(Bob,Sue,Lisa)
head(df)
```

```{r}
ggplot(df,aes(x = time,y=change,fill = person)) + 
  geom_area()
```

```{r}
df_wide <- df %>% 
  pivot_wider(id_cols = time,values_from = change, names_from = person)
df_wide
```
```{r}
df_wide$total <- 
  df_wide$Bob + 
  df_wide$Sue +
  df_wide$Lisa
df_wide$total
```

### Dumbbell Charts

```{r warning=FALSE}
library(ggalt)
df2 <- df %>% 
  filter(time == 1 | time == 5) %>% 
  pivot_wider(names_from = time,values_from = change) %>% 
  rename(year1 = `1`,year5 = `5`)
df2

```

```{r}
ggplot(df2,
       aes(y=person,
           x = year1,
           xend = year5)) + 
  geom_dumbbell()
```

Reorder the y axis

```{r}
ggplot(df2,
       aes(y=reorder(person,year1),
           x = year1,
           xend = year5)) + 
  geom_dumbbell(
    colour_x = "purple",
    colour_xend = "red",
    size_x = 3,
    size_xend = 3
  )
```

## Flows and Circles

### Alluvial Diagrams

```{r}
library(ggalluvial)
group1 <- tibble(groupid = groupid <- rep("group1",7),
                 studentID = sample(seq(from=1,to =20),7),
                 gender = sample(c("M","F"),7,replace = TRUE),
                 grades = sample(c("High pass","Pass","Fail"),7,replace = TRUE))

group2 <- tibble(groupid = groupid <- rep("group2",7),
                 studentID = sample(seq(from=21,to =30),7),
                 gender = sample(c("M","F"),7,replace = TRUE),
                 grades = sample(c("High pass","Pass","Fail"),7,replace = TRUE))

group3 <- tibble(groupid = groupid <- rep("group3",7),
                 studentID = sample(seq(from=31,to =40),7),
                 gender = sample(c("M","F"),7,replace = TRUE),
                 grades = sample(c("High pass","Pass","Fail"),7,replace = TRUE))

students <- bind_rows(group1,group2,group3)
head(students)
```

```{r}
students_table <- students %>% 
  group_by(groupid,gender,grades) %>% 
  count()
students_table
```

```{r}
ggplot(students_table,
       aes(axis1 = groupid,
           axis2 = grades,
           y=n)) + 
  geom_alluvium(aes(fill = gender)) + 
  geom_stratum() + 
  geom_text(stat = "stratum",aes(label = after_stat(stratum)))  
  # scale_fill_manual(values = c("purple","green"))
```

### Packed circle figure

```{r}
library(packcircles)
packing <- circleProgressiveLayout(members$all_pass,sizetype = "area")
members <- add_column(members,packing)
head(members)
```

Provides more points for ggplot to draw the perimeters of the circle

```{r fig.height=8, fig.width=15, warning=FALSE}
dat.gg <- circleLayoutVertices(packing,npoints = 50)
ggplot()+
  geom_polygon(data = dat.gg,
               aes( x= x,y = y,
                    group = id,
                    fill = as.factor(id),
                    alpha = 0.6)) + 
  geom_text(data = members,aes(
    x = x, y = y, size = all_pass,label = thomas_name))+
  theme(legend.position = "none") + 
  coord_equal() #makes your plot square
```

### Pie Charts

```{r}
prop <- c(3,7,9,1,2)
pie(prop)
```

